Agregue un Readme
LeonidasEsteban/platzi-video pull request #3
Opened 2019-12-19 17:59 UTC by Manenpren

Una descripción para incluirla en mis habilidades laborales, saludos!

2020-01-02 03:38 UTC, LeonidasEsteban requested changes

2020-01-02 03:38 UTC, LeonidasEsteban commented on README.md
> +* para realizar la misma se requirio utilizar los conocimientos aprendidos en los cursos de Fundamentos de Javascript, Reac.js, Redux resultando en el desarrollo de una aplicacion muy sencilla y func
...Fundamentos de Javascript, React.js, ...

2020-01-02 05:49 UTC, Manenpren reviewed
Lo siento!

2020-01-03 22:49 UTC, LeonidasEsteban requested changes

2020-01-03 22:49 UTC, LeonidasEsteban commented on README.md
> +* para realizar la misma se requirio utilizar los conocimientos aprendidos en los cursos de Fundamentos de Javascript, React.js, Redux resultando en el desarrollo de una aplicacion muy sencilla y fun
perdón, acabo de notar el requirió.

2020-01-03 23:38 UTC, Manenpren commented on README.md
> +* para realizar la misma se requirio utilizar los conocimientos aprendidos en los cursos de Fundamentos de Javascript, React.js, Redux resultando en el desarrollo de una aplicacion muy sencilla y fun
Si no supe si lo hice bien!

2020-02-14 18:23 UTC, closed without merging